FROM node:20

WORKDIR /app

COPY frontend /app
RUN npm install
RUN npm run build

# Usa un servidor estático como serve (opcional)
RUN npm install -g serve

EXPOSE 5173

CMD ["serve", "-s", "dist", "-l", "5173"]
