"""
Django settings for viviendas project.

Generated by 'django-admin startproject' using Django 5.2.1.
"""

import os
from pathlib import Path

# ────────────────────
# Rutas base
# ────────────────────
BASE_DIR = Path(__file__).resolve().parent.parent


# ────────────────────
# Configuración básica
# ────────────────────
SECRET_KEY = 'django-insecure-tzh+7g7+a&=h4qfb+m*)sd_bt&#rj^1ir&uon_b*o!a&g%+407'
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']  # Para desarrollo local


# ────────────────────
# Aplicaciones instaladas
# ────────────────────
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # Django REST Framework para APIs
    'corsheaders',     # Para manejar CORS
    'rest_framework.authtoken',

    # Apps del proyecto
    'home',
]

# ────────────────────
# Middleware
# ────────────────────
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # debe ir antes de CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'viviendas.urls'


# ────────────────────
# Templates
# ────────────────────
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],          # Dejamos vacío porque no usaremos templates propios
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'viviendas.wsgi.application'


# ────────────────────
# Base de datos
# ────────────────────
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ────────────────────
# Validación de contraseñas
# ────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ────────────────────
# Internacionalización
# ────────────────────
LANGUAGE_CODE = 'es-pe'
TIME_ZONE = 'America/Lima'
USE_I18N = True
USE_TZ = True


# ────────────────────
# Archivos estáticos
# ────────────────────
STATIC_URL = 'static/'
# STATICFILES_DIRS = []  # Sin carpeta estática adicional (evitamos warning)

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# ────────────────────
# Clave primaria automática
# ────────────────────
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [ 
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
  # Por defecto abierto, pero puedes ajustar
    ]
}
CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = ["http://localhost:5173"]

AUTH_USER_MODEL = 'home.Usuario'

