# Generated by Django 5.2.3 on 2025-07-04 22:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('departamento', models.CharField(max_length=80)),
                ('provincia', models.CharField(max_length=80)),
                ('distrito', models.CharField(max_length=80)),
                ('ubigeo', models.CharField(max_length=6)),
                ('beneficiarios', models.PositiveIntegerField(blank=True, null=True)),
                ('avance', models.PositiveSmallIntegerField(blank=True, help_text='Porcentaje de avance (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ifi', models.CharField(max_length=120)),
                ('tipo_ifi', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre_completo', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('pais', models.CharField(max_length=80)),
                ('provincia', models.CharField(max_length=80)),
                ('ciudad', models.CharField(max_length=80)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('recibir_email', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_actual', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
                ('email_enviado', models.BooleanField(default=False)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio_mail', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.proyecto')),
            ],
            options={
                'ordering': ['-fecha_evento'],
                'unique_together': {('usuario', 'proyecto', 'estado_actual')},
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.proyecto')),
            ],
            options={
                'ordering': ['-fecha_agregado'],
                'unique_together': {('usuario', 'proyecto')},
            },
        ),
    ]
